

export enum ElementType {
  SOURCE_CODE = 'SOURCE_CODE',
  TEXT = 'TEXT',
  BIG_TITLE = 'BIG_TITLE',
  MEDIUM_TITLE = 'MEDIUM_TITLE',
  SMALL_TITLE = 'SMALL_TITLE',
  VERY_SMALL_TITLE = 'VERY_SMALL_TITLE',
  CONTENT = 'CONTENT',
  LIST = 'LIST',
  ATTACHMENT= 'ATTACHMENT',
  HYPERLINK = 'HYPERLINK',
  ONE_CHOICE_QUESTION = 'ONE_CHOICE_QUESTION',
  MULTI_CHOICES_QUESTION = 'MULTI_CHOICES_QUESTION',
  SHORT_TEXT_QUESTION = 'SHORT_TEXT_QUESTION',
  LONG_TEXT_QUESTION = 'LONG_TEXT_QUESTION'
}
